apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret-service-app
  namespace: argocd
spec:
  source:
    targetRevision: HEAD
    path: deploy/argocd/environment/development
    