apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingress
  namespace: argocd  # Make sure this matches your ArgoCD namespace
spec:
  entryPoints:
    - argocd  # ✅ Use the new entryPoint
  routes:
    - match: PathPrefix(`/argocd`) # Replace with your K3s node's IP
      kind: Rule
      services:
        - name: argocd-server
          port: 80  # ArgoCD service port (default HTTP)