apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      argocd:
        port: 8085
        expose:
          enabled: true  # ✅ Correct
        exposedPort: 8085
