apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik.yaml: |
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
      argocd:
        address: ":8085"
    providers:
      kubernetesIngress: {}
      kubernetesCRD: {}