apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  source:
    targetRevision: development
    helm:
      valueFiles:
      - values.yaml
