apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../applications/argocd # 2
- ../../applications/data-collector-service #4
- ../../applications/rabbitmq-service #3
- ../../applications/sealed-secrets-service # 1
- root.yaml


patches:
- path: data-collector-service/target-patch.yaml
- path: rabbitmq-service/target-patch.yaml
- path: sealed-secrets-service/target-patch.yaml

