apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- root.yaml
- ../../applications/argocd
- ../../applications/data-collector-service
- ../../applications/rabbitmq-service

patches:
- path: data-collector-service/target-patch.yaml
- path: rabbitmq-service/target-patch.yaml
