apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- namespace.yaml
- private-repo-creds.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml


# helmCharts:
#   - name: argo-cd
#     version: stable  # Use a specific version or omit to get the latest
#     releaseName: argocd
#     namespace: argocd
#     valuesFile: values.yaml  # Path to your custom values.yaml file


patches:
  - path: argo-cmd-params-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
