apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- namespace.yaml
- private-repo-creds.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
  - path: argo-cmd-params-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
