apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-collector-service-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: git@github.com:alejandropriv/stock-data-collector-service
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd