apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-collector-service
  namespace: argocd

spec:
  project: default
  source:
    repoURL: git@github.com:alejandropriv/stock-data-collector-service
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd