apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: kaniko

spec:
  nodeSelector:
    "kubernetes.io/hostname": "minik-nodes-m02"
  containers:
  - name: kaniko
    image: nginx:latest
#    image: gcr.io/kaniko-project/executor:latest
#    args: [

#           "--dockerfile=Dockerfile",
#           "--context=dir:///workspace/",
#            "--no-push"] 

    volumeMounts:
      - name: dockerfile-storage
        mountPath: /dockerfiles
  restartPolicy: Never
  volumes:
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: dockerfile-claim
        
